In [5]:
import numpy as np
count = 0

#grid = [[9, 0, 6, 0, 7, 0, 4, 0, 3],
#       [0, 0, 0, 4, 0, 0, 2, 0, 0],
#       [0, 7, 0, 0, 2, 3, 0, 1, 0],
#       [5, 0, 0, 0, 0, 0, 1, 0, 0],
#       [0, 4, 0, 2, 0, 8, 0, 6, 0],
#       [0, 0, 3, 0, 0, 0, 0, 0, 5],
#       [0, 3, 0, 7, 0, 0, 0, 5, 0],
#       [0, 0, 7, 0, 0, 5, 0, 0, 0],
#       [4, 0, 5, 0, 1, 0, 7, 0, 8]]

#grid = [[ 0, 8, 0, 0, 9, 3, 0, 7, 0 ],
#        [6, 9, 0, 4, 7, 0, 0, 0, 2 ],
#        [0, 0, 1, 0, 0, 2, 6, 0, 0 ],
#        [0, 2, 0, 9, 3, 0, 0, 1, 0 ],
#        [9, 0, 0, 7, 0, 4, 0, 0, 5 ],
#        [7, 1, 0, 0, 2, 0, 0, 3, 0 ],
#        [0, 0, 8, 3, 0, 0, 1, 0, 7 ],
#        [3, 0, 9, 0, 0, 7, 0, 0, 8 ],
#        [0, 4, 0, 2, 5, 0, 0, 6, 9 ]]

grid = [[0, 0, 0, 8, 0, 0, 0, 0, 9 ],
        [0, 1, 9, 0, 0, 5, 8, 3, 0 ],
        [0, 4, 3, 0, 1, 0, 0, 0, 7 ],
        [4, 0, 0, 1, 5, 0, 0, 0, 3 ],
        [0, 0, 2, 7, 0, 4, 0, 1, 0 ],
        [0, 8, 0, 0, 9, 0, 6, 0, 0 ],
        [0, 7, 0, 0, 0, 6, 3, 0, 0 ],
        [0, 3, 0, 0, 7, 0, 0, 8, 0 ],
        [9, 0, 4, 5, 0, 0, 0, 0, 1 ]]

def possible(y,x,n):
    global grid
    # n is the number we want to fill in
    
    # check if n already existed in vertical (y) axis
    # if exists, return False (not possible)
    for i in range(9):
        if grid[y][i] == n:
            return False
    
    # check horizontal (x) axix
    for i in range(9):
        if grid[i][x] == n:
            return False
        
    #check the 3x3 sub grid
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(3):
        for j in range(3):
            if grid[y0+i][x0+j] == n:
                return False
    
    # return True if pass all 3 checks
    return True

def solve():
    global grid, count
    for y in range(9):
        for x in range(9):
            # find blank positions in the grid (value = 0)
            if grid[y][x] == 0:
                # loop n from 1-9
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x] = n
                        solve()
                        
                        # This is where backtracking happens
                        # Reset the latest position back to 0 and try with new n value
                        grid[y][x] = 0
                return
    count = count + 1
    print("id:{}".format(count))
    print(np.matrix(grid))
    # input('More?')
    
solve()

id:1
[[2 5 6 8 3 7 1 4 9]
 [7 1 9 2 4 5 8 3 6]
 [8 4 3 6 1 9 2 5 7]
 [4 6 7 1 5 8 9 2 3]
 [3 9 2 7 6 4 5 1 8]
 [5 8 1 3 9 2 6 7 4]
 [1 7 8 4 2 6 3 9 5]
 [6 3 5 9 7 1 4 8 2]
 [9 2 4 5 8 3 7 6 1]]
id:2
[[2 5 6 8 3 7 1 4 9]
 [7 1 9 4 2 5 8 3 6]
 [8 4 3 6 1 9 2 5 7]
 [4 6 7 1 5 8 9 2 3]
 [3 9 2 7 6 4 5 1 8]
 [5 8 1 3 9 2 6 7 4]
 [1 7 8 2 4 6 3 9 5]
 [6 3 5 9 7 1 4 8 2]
 [9 2 4 5 8 3 7 6 1]]
